#pragma once

#define TYPEINFO_MEMBER_FLAG_CSTRING  0x01

#include "platform.h"
// PlatformTexture
// PlatformFileLastWriteTime
#include "editor.h"
// Editor
#include "meat_space.h"
// MeatSpaceCommand_move_to
// MeatSpaceWeapon_gun
// MeatSpaceWeapon_grenade_launcher
// MeatSpaceWeapon_healing_ray
// MeatSpaceEntity
// MeatSpaceBrain_player
// MeatSpaceProjectile_common
// MeatSpaceProjectile_entity_targeted
// MeatSpaceProjectile_position_targeted
// MeatSpaceCamera
// PositionGridBucketNode
// CollisionVolume_common
// CollisionVolume_box
// CollisionVolume_circle
// CollisionVolume_elipse
// MeatSpaceEntityTemplate
// MeatSpaceEntityTemplateCollection
// MeatSpace
#include "assets.h"
// AssetAttributes
// AssetSpec
// TextureAsset
// PackedTexture
// ArchiveEntryHeader_texture_atlas
// GameArchiveHeader
#include "geometry.h"
// vec2
// ivec2
// vec3
// ivec3
// rect2
#include "game.h"
// GameState
// TransientState
#include "grid.h"
// GridCell
// Grid
#include "asset_manager.h"
// AssetManager
#include "memory.h"
// Allocator
enum TypeInfo_ID {
  TypeInfo_ID_none,

  TypeInfo_ID_void,

  TypeInfo_ID_u64,
  TypeInfo_ID_u32,
  TypeInfo_ID_u16,
  TypeInfo_ID_u8,
  TypeInfo_ID_i64,
  TypeInfo_ID_i32,
  TypeInfo_ID_i16,
  TypeInfo_ID_i8,
  TypeInfo_ID_b32,
  TypeInfo_ID_f32,
  TypeInfo_ID_f64,

  TypeInfo_ID_size_t,
  TypeInfo_ID_char,
  TypeInfo_ID_int,

  TypeInfo_ID_end_primitives,
  TypeInfo_ID_PlatformTexture,
  TypeInfo_ID_PlatformFileLastWriteTime,
  TypeInfo_ID_Editor,
  TypeInfo_ID_MeatSpaceCommand_Type,
  TypeInfo_ID_MeatSpaceCommand_move_to,
  TypeInfo_ID_MeatSpaceCommand,
  TypeInfo_ID_MeatSpaceWeapon_Type,
  TypeInfo_ID_MeatSpaceWeapon_gun,
  TypeInfo_ID_MeatSpaceWeapon_grenade_launcher,
  TypeInfo_ID_MeatSpaceWeapon_healing_ray,
  TypeInfo_ID_MeatSpaceWeapon,
  TypeInfo_ID_SelectionGroup,
  TypeInfo_ID_MeatSpaceEntityTemplateId,
  TypeInfo_ID_MeatSpaceEntity,
  TypeInfo_ID_MeatSpaceBrain_Type,
  TypeInfo_ID_MeatSpaceBrain_player,
  TypeInfo_ID_MeatSpaceBrain,
  TypeInfo_ID_MeatSpaceProjectile_Type,
  TypeInfo_ID_MeatSpaceProjectile_common,
  TypeInfo_ID_MeatSpaceProjectile_entity_targeted,
  TypeInfo_ID_MeatSpaceProjectile_position_targeted,
  TypeInfo_ID_MeatSpaceProjectile,
  TypeInfo_ID_MeatSpaceCamera,
  TypeInfo_ID_PositionGridBucketNode,
  TypeInfo_ID_CollisionVolume_Type,
  TypeInfo_ID_CollisionVolume_common,
  TypeInfo_ID_CollisionVolume_box,
  TypeInfo_ID_CollisionVolume_circle,
  TypeInfo_ID_CollisionVolume_elipse,
  TypeInfo_ID_CollisionVolume,
  TypeInfo_ID_MeatSpaceEntityTemplate,
  TypeInfo_ID_MeatSpaceEntityTemplateCollection,
  TypeInfo_ID_MeatSpace,
  TypeInfo_ID_AssetType,
  TypeInfo_ID_AssetDirection,
  TypeInfo_ID_AssetMoveState,
  TypeInfo_ID_AssetLivingState,
  TypeInfo_ID_AssetClass,
  TypeInfo_ID_AssetColor,
  TypeInfo_ID_AssetAttributes,
  TypeInfo_ID_AssetSpec,
  TypeInfo_ID_DummyUnion_Type,
  TypeInfo_ID_DummyUnion,
  TypeInfo_ID_TextureAsset,
  TypeInfo_ID_ArchiveEntryType,
  TypeInfo_ID_PackedTexture,
  TypeInfo_ID_ArchiveEntryHeader_texture_atlas,
  TypeInfo_ID_GameArchiveHeader,
  TypeInfo_ID_vec2,
  TypeInfo_ID_ivec2,
  TypeInfo_ID_vec3,
  TypeInfo_ID_ivec3,
  TypeInfo_ID_rect2,
  TypeInfo_ID_GameState,
  TypeInfo_ID_TransientState,
  TypeInfo_ID_GridCell,
  TypeInfo_ID_Grid,
  TypeInfo_ID_AssetManager,
  TypeInfo_ID_Allocator,

  TypeInfo_ID_count
};

enum TypeKind {
  TypeKind_struct,
  TypeKind_enum,
  TypeKind_union,
  TypeKind_primitive,
};

enum MemberKind {
  MemberKind_enum,
  MemberKind_array,
  MemberKind_pointer,
  MemberKind_array_of_pointers,
  MemberKind_value,
};

struct MemberInfo {
  char* member_name;
  TypeInfo_ID parent_type;
  TypeInfo_ID member_type;
  MemberKind member_kind;
  int enum_value;
  size_t offset;
  size_t array_size;
  char flags;
  int table_index;
};

MemberInfo TypeInfo_member_table[] = {
  {"width", TypeInfo_ID_PlatformTexture, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((PlatformTexture*)0)->width, 0, 0, 0},
  {"handle", TypeInfo_ID_PlatformTexture, TypeInfo_ID_void, MemberKind_pointer, 0, (size_t)&((PlatformTexture*)0)->handle, 0, 0, 1},
  {"platform_data", TypeInfo_ID_PlatformFileLastWriteTime, TypeInfo_ID_char, MemberKind_array, 0, (size_t)&((PlatformFileLastWriteTime*)0)->platform_data, ARRAY_LENGTH(((PlatformFileLastWriteTime*)0)->platform_data), 0, 2},
  {"MeatSpaceCommand_Type_none", TypeInfo_ID_MeatSpaceCommand_Type, TypeInfo_ID_i32, MemberKind_enum, 0, 0, 0, 0, 3},
  {"MeatSpaceCommand_Type_move_to", TypeInfo_ID_MeatSpaceCommand_Type, TypeInfo_ID_i32, MemberKind_enum, 1, 0, 0, 0, 4},
  {"MeatSpaceCommand_Type_count", TypeInfo_ID_MeatSpaceCommand_Type, TypeInfo_ID_i32, MemberKind_enum, 2, 0, 0, 0, 5},
  {"type", TypeInfo_ID_MeatSpaceCommand_move_to, TypeInfo_ID_MeatSpaceCommand_Type, MemberKind_value, 0, (size_t)&((MeatSpaceCommand_move_to*)0)->type, 0, 0, 6},
  {"target", TypeInfo_ID_MeatSpaceCommand_move_to, TypeInfo_ID_GridCell, MemberKind_value, 0, (size_t)&((MeatSpaceCommand_move_to*)0)->target, 0, 0, 7},
  {"type", TypeInfo_ID_MeatSpaceCommand, TypeInfo_ID_MeatSpaceCommand_Type, MemberKind_value, 0, (size_t)&((MeatSpaceCommand*)0)->type, 0, 0, 8},
  {"move_to", TypeInfo_ID_MeatSpaceCommand, TypeInfo_ID_MeatSpaceCommand_move_to, MemberKind_value, 0, (size_t)&((MeatSpaceCommand*)0)->move_to, 0, 0, 9},
  {"MeatSpaceWeapon_Type_none", TypeInfo_ID_MeatSpaceWeapon_Type, TypeInfo_ID_i32, MemberKind_enum, 0, 0, 0, 0, 10},
  {"MeatSpaceWeapon_Type_gun", TypeInfo_ID_MeatSpaceWeapon_Type, TypeInfo_ID_i32, MemberKind_enum, 1, 0, 0, 0, 11},
  {"MeatSpaceWeapon_Type_grenade_launcher", TypeInfo_ID_MeatSpaceWeapon_Type, TypeInfo_ID_i32, MemberKind_enum, 2, 0, 0, 0, 12},
  {"MeatSpaceWeapon_Type_healing_ray", TypeInfo_ID_MeatSpaceWeapon_Type, TypeInfo_ID_i32, MemberKind_enum, 3, 0, 0, 0, 13},
  {"type", TypeInfo_ID_MeatSpaceWeapon_gun, TypeInfo_ID_MeatSpaceWeapon_Type, MemberKind_value, 0, (size_t)&((MeatSpaceWeapon_gun*)0)->type, 0, 0, 14},
  {"damage", TypeInfo_ID_MeatSpaceWeapon_gun, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((MeatSpaceWeapon_gun*)0)->damage, 0, 0, 15},
  {"range", TypeInfo_ID_MeatSpaceWeapon_gun, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((MeatSpaceWeapon_gun*)0)->range, 0, 0, 16},
  {"cooldown", TypeInfo_ID_MeatSpaceWeapon_gun, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((MeatSpaceWeapon_gun*)0)->cooldown, 0, 0, 17},
  {"time_since_last_fired", TypeInfo_ID_MeatSpaceWeapon_gun, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((MeatSpaceWeapon_gun*)0)->time_since_last_fired, 0, 0, 18},
  {"type", TypeInfo_ID_MeatSpaceWeapon_grenade_launcher, TypeInfo_ID_MeatSpaceWeapon_Type, MemberKind_value, 0, (size_t)&((MeatSpaceWeapon_grenade_launcher*)0)->type, 0, 0, 19},
  {"damage", TypeInfo_ID_MeatSpaceWeapon_grenade_launcher, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((MeatSpaceWeapon_grenade_launcher*)0)->damage, 0, 0, 20},
  {"range", TypeInfo_ID_MeatSpaceWeapon_grenade_launcher, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((MeatSpaceWeapon_grenade_launcher*)0)->range, 0, 0, 21},
  {"cooldown", TypeInfo_ID_MeatSpaceWeapon_grenade_launcher, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((MeatSpaceWeapon_grenade_launcher*)0)->cooldown, 0, 0, 22},
  {"time_since_last_fired", TypeInfo_ID_MeatSpaceWeapon_grenade_launcher, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((MeatSpaceWeapon_grenade_launcher*)0)->time_since_last_fired, 0, 0, 23},
  {"radius", TypeInfo_ID_MeatSpaceWeapon_grenade_launcher, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((MeatSpaceWeapon_grenade_launcher*)0)->radius, 0, 0, 24},
  {"type", TypeInfo_ID_MeatSpaceWeapon_healing_ray, TypeInfo_ID_MeatSpaceWeapon_Type, MemberKind_value, 0, (size_t)&((MeatSpaceWeapon_healing_ray*)0)->type, 0, 0, 25},
  {"damage", TypeInfo_ID_MeatSpaceWeapon_healing_ray, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((MeatSpaceWeapon_healing_ray*)0)->damage, 0, 0, 26},
  {"range", TypeInfo_ID_MeatSpaceWeapon_healing_ray, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((MeatSpaceWeapon_healing_ray*)0)->range, 0, 0, 27},
  {"cooldown", TypeInfo_ID_MeatSpaceWeapon_healing_ray, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((MeatSpaceWeapon_healing_ray*)0)->cooldown, 0, 0, 28},
  {"time_since_last_fired", TypeInfo_ID_MeatSpaceWeapon_healing_ray, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((MeatSpaceWeapon_healing_ray*)0)->time_since_last_fired, 0, 0, 29},
  {"type", TypeInfo_ID_MeatSpaceWeapon, TypeInfo_ID_MeatSpaceWeapon_Type, MemberKind_value, 0, (size_t)&((MeatSpaceWeapon*)0)->type, 0, 0, 30},
  {"gun", TypeInfo_ID_MeatSpaceWeapon, TypeInfo_ID_MeatSpaceWeapon_gun, MemberKind_value, 0, (size_t)&((MeatSpaceWeapon*)0)->gun, 0, 0, 31},
  {"grenade_launcher", TypeInfo_ID_MeatSpaceWeapon, TypeInfo_ID_MeatSpaceWeapon_grenade_launcher, MemberKind_value, 0, (size_t)&((MeatSpaceWeapon*)0)->grenade_launcher, 0, 0, 32},
  {"healing_ray", TypeInfo_ID_MeatSpaceWeapon, TypeInfo_ID_MeatSpaceWeapon_healing_ray, MemberKind_value, 0, (size_t)&((MeatSpaceWeapon*)0)->healing_ray, 0, 0, 33},
  {"SelectionGroup_none", TypeInfo_ID_SelectionGroup, TypeInfo_ID_i32, MemberKind_enum, 0, 0, 0, 0, 34},
  {"SelectionGroup_player", TypeInfo_ID_SelectionGroup, TypeInfo_ID_i32, MemberKind_enum, 1, 0, 0, 0, 35},
  {"SelectionGroup_nonplayer", TypeInfo_ID_SelectionGroup, TypeInfo_ID_i32, MemberKind_enum, 2, 0, 0, 0, 36},
  {"SelectionGroup_enemy", TypeInfo_ID_SelectionGroup, TypeInfo_ID_i32, MemberKind_enum, 3, 0, 0, 0, 37},
  {"MeatSpaceEntityTemplateId_none", TypeInfo_ID_MeatSpaceEntityTemplateId, TypeInfo_ID_i32, MemberKind_enum, 0, 0, 0, 0, 38},
  {"MeatSpaceEntityTemplateId_tile", TypeInfo_ID_MeatSpaceEntityTemplateId, TypeInfo_ID_i32, MemberKind_enum, 1, 0, 0, 0, 39},
  {"MeatSpaceEntityTemplateId_crew_gun", TypeInfo_ID_MeatSpaceEntityTemplateId, TypeInfo_ID_i32, MemberKind_enum, 2, 0, 0, 0, 40},
  {"MeatSpaceEntityTemplateId_crew_healing_ray", TypeInfo_ID_MeatSpaceEntityTemplateId, TypeInfo_ID_i32, MemberKind_enum, 3, 0, 0, 0, 41},
  {"MeatSpaceEntityTemplateId_crew_grenade_launcher", TypeInfo_ID_MeatSpaceEntityTemplateId, TypeInfo_ID_i32, MemberKind_enum, 4, 0, 0, 0, 42},
  {"MeatSpaceEntityTemplateId_boulder_small", TypeInfo_ID_MeatSpaceEntityTemplateId, TypeInfo_ID_i32, MemberKind_enum, 5, 0, 0, 0, 43},
  {"MeatSpaceEntityTemplateId_boulder_large", TypeInfo_ID_MeatSpaceEntityTemplateId, TypeInfo_ID_i32, MemberKind_enum, 6, 0, 0, 0, 44},
  {"MeatSpaceEntityTemplateId_tree_medium", TypeInfo_ID_MeatSpaceEntityTemplateId, TypeInfo_ID_i32, MemberKind_enum, 7, 0, 0, 0, 45},
  {"MeatSpaceEntityTemplateId_tree_large", TypeInfo_ID_MeatSpaceEntityTemplateId, TypeInfo_ID_i32, MemberKind_enum, 8, 0, 0, 0, 46},
  {"id", TypeInfo_ID_MeatSpaceEntity, TypeInfo_ID_i64, MemberKind_value, 0, (size_t)&((MeatSpaceEntity*)0)->id, 0, 0, 47},
  {"p", TypeInfo_ID_MeatSpaceEntity, TypeInfo_ID_vec2, MemberKind_value, 0, (size_t)&((MeatSpaceEntity*)0)->p, 0, 0, 48},
  {"flags", TypeInfo_ID_MeatSpaceEntity, TypeInfo_ID_u32, MemberKind_value, 0, (size_t)&((MeatSpaceEntity*)0)->flags, 0, 0, 49},
  {"asset_type", TypeInfo_ID_MeatSpaceEntity, TypeInfo_ID_AssetType, MemberKind_value, 0, (size_t)&((MeatSpaceEntity*)0)->asset_type, 0, 0, 50},
  {"asset_attributes", TypeInfo_ID_MeatSpaceEntity, TypeInfo_ID_AssetAttributes, MemberKind_value, 0, (size_t)&((MeatSpaceEntity*)0)->asset_attributes, 0, 0, 51},
  {"z_bias", TypeInfo_ID_MeatSpaceEntity, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((MeatSpaceEntity*)0)->z_bias, 0, 0, 52},
  {"selection_group", TypeInfo_ID_MeatSpaceEntity, TypeInfo_ID_SelectionGroup, MemberKind_value, 0, (size_t)&((MeatSpaceEntity*)0)->selection_group, 0, 0, 53},
  {"selected", TypeInfo_ID_MeatSpaceEntity, TypeInfo_ID_b32, MemberKind_value, 0, (size_t)&((MeatSpaceEntity*)0)->selected, 0, 0, 54},
  {"selection_bounds", TypeInfo_ID_MeatSpaceEntity, TypeInfo_ID_rect2, MemberKind_value, 0, (size_t)&((MeatSpaceEntity*)0)->selection_bounds, 0, 0, 55},
  {"collision_volumes", TypeInfo_ID_MeatSpaceEntity, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((MeatSpaceEntity*)0)->collision_volumes, 0, 0, 56},
  {"target_center", TypeInfo_ID_MeatSpaceEntity, TypeInfo_ID_vec2, MemberKind_value, 0, (size_t)&((MeatSpaceEntity*)0)->target_center, 0, 0, 57},
  {"firing_center", TypeInfo_ID_MeatSpaceEntity, TypeInfo_ID_vec2, MemberKind_value, 0, (size_t)&((MeatSpaceEntity*)0)->firing_center, 0, 0, 58},
  {"max_health", TypeInfo_ID_MeatSpaceEntity, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((MeatSpaceEntity*)0)->max_health, 0, 0, 59},
  {"health", TypeInfo_ID_MeatSpaceEntity, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((MeatSpaceEntity*)0)->health, 0, 0, 60},
  {"weapon", TypeInfo_ID_MeatSpaceEntity, TypeInfo_ID_MeatSpaceWeapon, MemberKind_value, 0, (size_t)&((MeatSpaceEntity*)0)->weapon, 0, 0, 61},
  {"unfinished_move", TypeInfo_ID_MeatSpaceEntity, TypeInfo_ID_b32, MemberKind_value, 0, (size_t)&((MeatSpaceEntity*)0)->unfinished_move, 0, 0, 62},
  {"unfinished_move_target", TypeInfo_ID_MeatSpaceEntity, TypeInfo_ID_GridCell, MemberKind_value, 0, (size_t)&((MeatSpaceEntity*)0)->unfinished_move_target, 0, 0, 63},
  {"template_id", TypeInfo_ID_MeatSpaceEntity, TypeInfo_ID_MeatSpaceEntityTemplateId, MemberKind_value, 0, (size_t)&((MeatSpaceEntity*)0)->template_id, 0, 0, 64},
  {"texture_anchor", TypeInfo_ID_MeatSpaceEntity, TypeInfo_ID_vec2, MemberKind_value, 0, (size_t)&((MeatSpaceEntity*)0)->texture_anchor, 0, 0, 65},
  {"command", TypeInfo_ID_MeatSpaceEntity, TypeInfo_ID_MeatSpaceCommand, MemberKind_value, 0, (size_t)&((MeatSpaceEntity*)0)->command, 0, 0, 66},
  {"MeatSpaceBrain_Type_none", TypeInfo_ID_MeatSpaceBrain_Type, TypeInfo_ID_i32, MemberKind_enum, 0, 0, 0, 0, 67},
  {"MeatSpaceBrain_Type_player", TypeInfo_ID_MeatSpaceBrain_Type, TypeInfo_ID_i32, MemberKind_enum, 1, 0, 0, 0, 68},
  {"MeatSpaceBrain_Type_count", TypeInfo_ID_MeatSpaceBrain_Type, TypeInfo_ID_i32, MemberKind_enum, 2, 0, 0, 0, 69},
  {"type", TypeInfo_ID_MeatSpaceBrain_player, TypeInfo_ID_MeatSpaceBrain_Type, MemberKind_value, 0, (size_t)&((MeatSpaceBrain_player*)0)->type, 0, 0, 70},
  {"selected_entities_count", TypeInfo_ID_MeatSpaceBrain_player, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((MeatSpaceBrain_player*)0)->selected_entities_count, 0, 0, 71},
  {"selected_entities", TypeInfo_ID_MeatSpaceBrain_player, TypeInfo_ID_i64, MemberKind_pointer, 0, (size_t)&((MeatSpaceBrain_player*)0)->selected_entities, 0, 0, 72},
  {"mouse_down_entity", TypeInfo_ID_MeatSpaceBrain_player, TypeInfo_ID_MeatSpaceEntity, MemberKind_pointer, 0, (size_t)&((MeatSpaceBrain_player*)0)->mouse_down_entity, 0, 0, 73},
  {"selecting", TypeInfo_ID_MeatSpaceBrain_player, TypeInfo_ID_b32, MemberKind_value, 0, (size_t)&((MeatSpaceBrain_player*)0)->selecting, 0, 0, 74},
  {"selection_start", TypeInfo_ID_MeatSpaceBrain_player, TypeInfo_ID_vec2, MemberKind_value, 0, (size_t)&((MeatSpaceBrain_player*)0)->selection_start, 0, 0, 75},
  {"type", TypeInfo_ID_MeatSpaceBrain, TypeInfo_ID_MeatSpaceBrain_Type, MemberKind_value, 0, (size_t)&((MeatSpaceBrain*)0)->type, 0, 0, 76},
  {"player", TypeInfo_ID_MeatSpaceBrain, TypeInfo_ID_MeatSpaceBrain_player, MemberKind_value, 0, (size_t)&((MeatSpaceBrain*)0)->player, 0, 0, 77},
  {"MeatSpaceProjectile_Type_none", TypeInfo_ID_MeatSpaceProjectile_Type, TypeInfo_ID_i32, MemberKind_enum, 0, 0, 0, 0, 78},
  {"MeatSpaceProjectile_Type_common", TypeInfo_ID_MeatSpaceProjectile_Type, TypeInfo_ID_i32, MemberKind_enum, 1, 0, 0, 0, 79},
  {"MeatSpaceProjectile_Type_entity_targeted", TypeInfo_ID_MeatSpaceProjectile_Type, TypeInfo_ID_i32, MemberKind_enum, 2, 0, 0, 0, 80},
  {"MeatSpaceProjectile_Type_position_targeted", TypeInfo_ID_MeatSpaceProjectile_Type, TypeInfo_ID_i32, MemberKind_enum, 3, 0, 0, 0, 81},
  {"type", TypeInfo_ID_MeatSpaceProjectile_common, TypeInfo_ID_MeatSpaceProjectile_Type, MemberKind_value, 0, (size_t)&((MeatSpaceProjectile_common*)0)->type, 0, 0, 82},
  {"p", TypeInfo_ID_MeatSpaceProjectile_common, TypeInfo_ID_vec2, MemberKind_value, 0, (size_t)&((MeatSpaceProjectile_common*)0)->p, 0, 0, 83},
  {"type", TypeInfo_ID_MeatSpaceProjectile_entity_targeted, TypeInfo_ID_MeatSpaceProjectile_Type, MemberKind_value, 0, (size_t)&((MeatSpaceProjectile_entity_targeted*)0)->type, 0, 0, 84},
  {"p", TypeInfo_ID_MeatSpaceProjectile_entity_targeted, TypeInfo_ID_vec2, MemberKind_value, 0, (size_t)&((MeatSpaceProjectile_entity_targeted*)0)->p, 0, 0, 85},
  {"target_entity", TypeInfo_ID_MeatSpaceProjectile_entity_targeted, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((MeatSpaceProjectile_entity_targeted*)0)->target_entity, 0, 0, 86},
  {"speed", TypeInfo_ID_MeatSpaceProjectile_entity_targeted, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((MeatSpaceProjectile_entity_targeted*)0)->speed, 0, 0, 87},
  {"damage", TypeInfo_ID_MeatSpaceProjectile_entity_targeted, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((MeatSpaceProjectile_entity_targeted*)0)->damage, 0, 0, 88},
  {"type", TypeInfo_ID_MeatSpaceProjectile_position_targeted, TypeInfo_ID_MeatSpaceProjectile_Type, MemberKind_value, 0, (size_t)&((MeatSpaceProjectile_position_targeted*)0)->type, 0, 0, 89},
  {"p", TypeInfo_ID_MeatSpaceProjectile_position_targeted, TypeInfo_ID_vec2, MemberKind_value, 0, (size_t)&((MeatSpaceProjectile_position_targeted*)0)->p, 0, 0, 90},
  {"target_p", TypeInfo_ID_MeatSpaceProjectile_position_targeted, TypeInfo_ID_vec2, MemberKind_value, 0, (size_t)&((MeatSpaceProjectile_position_targeted*)0)->target_p, 0, 0, 91},
  {"speed", TypeInfo_ID_MeatSpaceProjectile_position_targeted, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((MeatSpaceProjectile_position_targeted*)0)->speed, 0, 0, 92},
  {"type", TypeInfo_ID_MeatSpaceProjectile, TypeInfo_ID_MeatSpaceProjectile_Type, MemberKind_value, 0, (size_t)&((MeatSpaceProjectile*)0)->type, 0, 0, 93},
  {"common", TypeInfo_ID_MeatSpaceProjectile, TypeInfo_ID_MeatSpaceProjectile_common, MemberKind_value, 0, (size_t)&((MeatSpaceProjectile*)0)->common, 0, 0, 94},
  {"entity_targeted", TypeInfo_ID_MeatSpaceProjectile, TypeInfo_ID_MeatSpaceProjectile_entity_targeted, MemberKind_value, 0, (size_t)&((MeatSpaceProjectile*)0)->entity_targeted, 0, 0, 95},
  {"position_targeted", TypeInfo_ID_MeatSpaceProjectile, TypeInfo_ID_MeatSpaceProjectile_position_targeted, MemberKind_value, 0, (size_t)&((MeatSpaceProjectile*)0)->position_targeted, 0, 0, 96},
  {"position", TypeInfo_ID_MeatSpaceCamera, TypeInfo_ID_vec2, MemberKind_value, 0, (size_t)&((MeatSpaceCamera*)0)->position, 0, 0, 97},
  {"scale", TypeInfo_ID_MeatSpaceCamera, TypeInfo_ID_vec2, MemberKind_value, 0, (size_t)&((MeatSpaceCamera*)0)->scale, 0, 0, 98},
  {"viewport_top", TypeInfo_ID_MeatSpaceCamera, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((MeatSpaceCamera*)0)->viewport_top, 0, 0, 99},
  {"viewport_bottom", TypeInfo_ID_MeatSpaceCamera, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((MeatSpaceCamera*)0)->viewport_bottom, 0, 0, 100},
  {"viewport_left", TypeInfo_ID_MeatSpaceCamera, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((MeatSpaceCamera*)0)->viewport_left, 0, 0, 101},
  {"viewport_right", TypeInfo_ID_MeatSpaceCamera, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((MeatSpaceCamera*)0)->viewport_right, 0, 0, 102},
  {"entity_index_plus_one", TypeInfo_ID_PositionGridBucketNode, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((PositionGridBucketNode*)0)->entity_index_plus_one, 0, 0, 103},
  {"next_bucket_plus_one", TypeInfo_ID_PositionGridBucketNode, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((PositionGridBucketNode*)0)->next_bucket_plus_one, 0, 0, 104},
  {"CollisionVolume_Type_none", TypeInfo_ID_CollisionVolume_Type, TypeInfo_ID_i32, MemberKind_enum, 0, 0, 0, 0, 105},
  {"CollisionVolume_Type_box", TypeInfo_ID_CollisionVolume_Type, TypeInfo_ID_i32, MemberKind_enum, 1, 0, 0, 0, 106},
  {"CollisionVolume_Type_common", TypeInfo_ID_CollisionVolume_Type, TypeInfo_ID_i32, MemberKind_enum, 2, 0, 0, 0, 107},
  {"CollisionVolume_Type_circle", TypeInfo_ID_CollisionVolume_Type, TypeInfo_ID_i32, MemberKind_enum, 3, 0, 0, 0, 108},
  {"CollisionVolume_Type_elipse", TypeInfo_ID_CollisionVolume_Type, TypeInfo_ID_i32, MemberKind_enum, 4, 0, 0, 0, 109},
  {"type", TypeInfo_ID_CollisionVolume_common, TypeInfo_ID_CollisionVolume_Type, MemberKind_value, 0, (size_t)&((CollisionVolume_common*)0)->type, 0, 0, 110},
  {"entity_id", TypeInfo_ID_CollisionVolume_common, TypeInfo_ID_i64, MemberKind_value, 0, (size_t)&((CollisionVolume_common*)0)->entity_id, 0, 0, 111},
  {"offset", TypeInfo_ID_CollisionVolume_common, TypeInfo_ID_vec2, MemberKind_value, 0, (size_t)&((CollisionVolume_common*)0)->offset, 0, 0, 112},
  {"type", TypeInfo_ID_CollisionVolume_box, TypeInfo_ID_CollisionVolume_Type, MemberKind_value, 0, (size_t)&((CollisionVolume_box*)0)->type, 0, 0, 113},
  {"entity_id", TypeInfo_ID_CollisionVolume_box, TypeInfo_ID_i64, MemberKind_value, 0, (size_t)&((CollisionVolume_box*)0)->entity_id, 0, 0, 114},
  {"offset", TypeInfo_ID_CollisionVolume_box, TypeInfo_ID_vec2, MemberKind_value, 0, (size_t)&((CollisionVolume_box*)0)->offset, 0, 0, 115},
  {"dimensions", TypeInfo_ID_CollisionVolume_box, TypeInfo_ID_vec2, MemberKind_value, 0, (size_t)&((CollisionVolume_box*)0)->dimensions, 0, 0, 116},
  {"type", TypeInfo_ID_CollisionVolume_circle, TypeInfo_ID_CollisionVolume_Type, MemberKind_value, 0, (size_t)&((CollisionVolume_circle*)0)->type, 0, 0, 117},
  {"entity_id", TypeInfo_ID_CollisionVolume_circle, TypeInfo_ID_i64, MemberKind_value, 0, (size_t)&((CollisionVolume_circle*)0)->entity_id, 0, 0, 118},
  {"offset", TypeInfo_ID_CollisionVolume_circle, TypeInfo_ID_vec2, MemberKind_value, 0, (size_t)&((CollisionVolume_circle*)0)->offset, 0, 0, 119},
  {"radius", TypeInfo_ID_CollisionVolume_circle, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((CollisionVolume_circle*)0)->radius, 0, 0, 120},
  {"type", TypeInfo_ID_CollisionVolume_elipse, TypeInfo_ID_CollisionVolume_Type, MemberKind_value, 0, (size_t)&((CollisionVolume_elipse*)0)->type, 0, 0, 121},
  {"entity_id", TypeInfo_ID_CollisionVolume_elipse, TypeInfo_ID_i64, MemberKind_value, 0, (size_t)&((CollisionVolume_elipse*)0)->entity_id, 0, 0, 122},
  {"offset", TypeInfo_ID_CollisionVolume_elipse, TypeInfo_ID_vec2, MemberKind_value, 0, (size_t)&((CollisionVolume_elipse*)0)->offset, 0, 0, 123},
  {"type", TypeInfo_ID_CollisionVolume, TypeInfo_ID_CollisionVolume_Type, MemberKind_value, 0, (size_t)&((CollisionVolume*)0)->type, 0, 0, 124},
  {"common", TypeInfo_ID_CollisionVolume, TypeInfo_ID_CollisionVolume_common, MemberKind_value, 0, (size_t)&((CollisionVolume*)0)->common, 0, 0, 125},
  {"box", TypeInfo_ID_CollisionVolume, TypeInfo_ID_CollisionVolume_box, MemberKind_value, 0, (size_t)&((CollisionVolume*)0)->box, 0, 0, 126},
  {"circle", TypeInfo_ID_CollisionVolume, TypeInfo_ID_CollisionVolume_circle, MemberKind_value, 0, (size_t)&((CollisionVolume*)0)->circle, 0, 0, 127},
  {"elipse", TypeInfo_ID_CollisionVolume, TypeInfo_ID_CollisionVolume_elipse, MemberKind_value, 0, (size_t)&((CollisionVolume*)0)->elipse, 0, 0, 128},
  {"id", TypeInfo_ID_MeatSpaceEntityTemplate, TypeInfo_ID_MeatSpaceEntityTemplateId, MemberKind_value, 0, (size_t)&((MeatSpaceEntityTemplate*)0)->id, 0, 0, 129},
  {"flags", TypeInfo_ID_MeatSpaceEntityTemplate, TypeInfo_ID_u32, MemberKind_value, 0, (size_t)&((MeatSpaceEntityTemplate*)0)->flags, 0, 0, 130},
  {"asset_type", TypeInfo_ID_MeatSpaceEntityTemplate, TypeInfo_ID_AssetType, MemberKind_value, 0, (size_t)&((MeatSpaceEntityTemplate*)0)->asset_type, 0, 0, 131},
  {"z_bias", TypeInfo_ID_MeatSpaceEntityTemplate, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((MeatSpaceEntityTemplate*)0)->z_bias, 0, 0, 132},
  {"selection_bounds", TypeInfo_ID_MeatSpaceEntityTemplate, TypeInfo_ID_rect2, MemberKind_value, 0, (size_t)&((MeatSpaceEntityTemplate*)0)->selection_bounds, 0, 0, 133},
  {"collision_volumes", TypeInfo_ID_MeatSpaceEntityTemplate, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((MeatSpaceEntityTemplate*)0)->collision_volumes, 0, 0, 134},
  {"target_center", TypeInfo_ID_MeatSpaceEntityTemplate, TypeInfo_ID_vec2, MemberKind_value, 0, (size_t)&((MeatSpaceEntityTemplate*)0)->target_center, 0, 0, 135},
  {"firing_center", TypeInfo_ID_MeatSpaceEntityTemplate, TypeInfo_ID_vec2, MemberKind_value, 0, (size_t)&((MeatSpaceEntityTemplate*)0)->firing_center, 0, 0, 136},
  {"weapon", TypeInfo_ID_MeatSpaceEntityTemplate, TypeInfo_ID_MeatSpaceWeapon, MemberKind_value, 0, (size_t)&((MeatSpaceEntityTemplate*)0)->weapon, 0, 0, 137},
  {"texture_anchor", TypeInfo_ID_MeatSpaceEntityTemplate, TypeInfo_ID_vec2, MemberKind_value, 0, (size_t)&((MeatSpaceEntityTemplate*)0)->texture_anchor, 0, 0, 138},
  {"max_health", TypeInfo_ID_MeatSpaceEntityTemplate, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((MeatSpaceEntityTemplate*)0)->max_health, 0, 0, 139},
  {"editing", TypeInfo_ID_MeatSpaceEntityTemplate, TypeInfo_ID_b32, MemberKind_value, 0, (size_t)&((MeatSpaceEntityTemplate*)0)->editing, 0, 0, 140},
  {"templates", TypeInfo_ID_MeatSpaceEntityTemplateCollection, TypeInfo_ID_MeatSpaceEntityTemplate, MemberKind_pointer, 0, (size_t)&((MeatSpaceEntityTemplateCollection*)0)->templates, 0, 0, 141},
  {"templates_count", TypeInfo_ID_MeatSpaceEntityTemplateCollection, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((MeatSpaceEntityTemplateCollection*)0)->templates_count, 0, 0, 142},
  {"collision_volumes", TypeInfo_ID_MeatSpaceEntityTemplateCollection, TypeInfo_ID_CollisionVolume, MemberKind_pointer, 0, (size_t)&((MeatSpaceEntityTemplateCollection*)0)->collision_volumes, 0, 0, 143},
  {"collision_volumes_count", TypeInfo_ID_MeatSpaceEntityTemplateCollection, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((MeatSpaceEntityTemplateCollection*)0)->collision_volumes_count, 0, 0, 144},
  {"entities", TypeInfo_ID_MeatSpace, TypeInfo_ID_MeatSpaceEntity, MemberKind_array, 0, (size_t)&((MeatSpace*)0)->entities, ARRAY_LENGTH(((MeatSpace*)0)->entities), 0, 145},
  {"entities_count", TypeInfo_ID_MeatSpace, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((MeatSpace*)0)->entities_count, 0, 0, 146},
  {"brains", TypeInfo_ID_MeatSpace, TypeInfo_ID_MeatSpaceBrain, MemberKind_array, 0, (size_t)&((MeatSpace*)0)->brains, ARRAY_LENGTH(((MeatSpace*)0)->brains), 0, 147},
  {"brains_count", TypeInfo_ID_MeatSpace, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((MeatSpace*)0)->brains_count, 0, 0, 148},
  {"projectiles", TypeInfo_ID_MeatSpace, TypeInfo_ID_MeatSpaceProjectile, MemberKind_array, 0, (size_t)&((MeatSpace*)0)->projectiles, ARRAY_LENGTH(((MeatSpace*)0)->projectiles), 0, 149},
  {"projectiles_count", TypeInfo_ID_MeatSpace, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((MeatSpace*)0)->projectiles_count, 0, 0, 150},
  {"projectiles_free_stack", TypeInfo_ID_MeatSpace, TypeInfo_ID_u32, MemberKind_array, 0, (size_t)&((MeatSpace*)0)->projectiles_free_stack, ARRAY_LENGTH(((MeatSpace*)0)->projectiles_free_stack), 0, 151},
  {"projectiles_free_stack_count", TypeInfo_ID_MeatSpace, TypeInfo_ID_u32, MemberKind_value, 0, (size_t)&((MeatSpace*)0)->projectiles_free_stack_count, 0, 0, 152},
  {"collision_volumes", TypeInfo_ID_MeatSpace, TypeInfo_ID_CollisionVolume, MemberKind_array, 0, (size_t)&((MeatSpace*)0)->collision_volumes, ARRAY_LENGTH(((MeatSpace*)0)->collision_volumes), 0, 153},
  {"collision_volumes_count", TypeInfo_ID_MeatSpace, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((MeatSpace*)0)->collision_volumes_count, 0, 0, 154},
  {"grid", TypeInfo_ID_MeatSpace, TypeInfo_ID_Grid, MemberKind_value, 0, (size_t)&((MeatSpace*)0)->grid, 0, 0, 155},
  {"position_grid", TypeInfo_ID_MeatSpace, TypeInfo_ID_i32, MemberKind_array, 0, (size_t)&((MeatSpace*)0)->position_grid, ARRAY_LENGTH(((MeatSpace*)0)->position_grid), 0, 156},
  {"position_grid_buckets", TypeInfo_ID_MeatSpace, TypeInfo_ID_PositionGridBucketNode, MemberKind_array, 0, (size_t)&((MeatSpace*)0)->position_grid_buckets, ARRAY_LENGTH(((MeatSpace*)0)->position_grid_buckets), 0, 157},
  {"position_grid_bucket_index", TypeInfo_ID_MeatSpace, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((MeatSpace*)0)->position_grid_bucket_index, 0, 0, 158},
  {"template_collection", TypeInfo_ID_MeatSpace, TypeInfo_ID_MeatSpaceEntityTemplateCollection, MemberKind_value, 0, (size_t)&((MeatSpace*)0)->template_collection, 0, 0, 159},
  {"camera", TypeInfo_ID_MeatSpace, TypeInfo_ID_MeatSpaceCamera, MemberKind_value, 0, (size_t)&((MeatSpace*)0)->camera, 0, 0, 160},
  {"AssetType_unspecified", TypeInfo_ID_AssetType, TypeInfo_ID_i32, MemberKind_enum, 0, 0, 0, 0, 161},
  {"AssetType_square", TypeInfo_ID_AssetType, TypeInfo_ID_i32, MemberKind_enum, 1, 0, 0, 0, 162},
  {"AssetType_crew", TypeInfo_ID_AssetType, TypeInfo_ID_i32, MemberKind_enum, 2, 0, 0, 0, 163},
  {"AssetType_selection_line", TypeInfo_ID_AssetType, TypeInfo_ID_i32, MemberKind_enum, 3, 0, 0, 0, 164},
  {"AssetType_selection_circle", TypeInfo_ID_AssetType, TypeInfo_ID_i32, MemberKind_enum, 4, 0, 0, 0, 165},
  {"AssetType_tile", TypeInfo_ID_AssetType, TypeInfo_ID_i32, MemberKind_enum, 5, 0, 0, 0, 166},
  {"AssetType_boulder_small", TypeInfo_ID_AssetType, TypeInfo_ID_i32, MemberKind_enum, 6, 0, 0, 0, 167},
  {"AssetType_boulder_large", TypeInfo_ID_AssetType, TypeInfo_ID_i32, MemberKind_enum, 7, 0, 0, 0, 168},
  {"AssetType_tree_medium", TypeInfo_ID_AssetType, TypeInfo_ID_i32, MemberKind_enum, 8, 0, 0, 0, 169},
  {"AssetType_tree_large", TypeInfo_ID_AssetType, TypeInfo_ID_i32, MemberKind_enum, 9, 0, 0, 0, 170},
  {"AssetType_count", TypeInfo_ID_AssetType, TypeInfo_ID_i32, MemberKind_enum, 10, 0, 0, 0, 171},
  {"AssetDirection_unspecified", TypeInfo_ID_AssetDirection, TypeInfo_ID_i32, MemberKind_enum, 0, 0, 0, 0, 172},
  {"AssetDirection_left", TypeInfo_ID_AssetDirection, TypeInfo_ID_i32, MemberKind_enum, 1, 0, 0, 0, 173},
  {"AssetDirection_right", TypeInfo_ID_AssetDirection, TypeInfo_ID_i32, MemberKind_enum, 2, 0, 0, 0, 174},
  {"AssetDirection_forward", TypeInfo_ID_AssetDirection, TypeInfo_ID_i32, MemberKind_enum, 3, 0, 0, 0, 175},
  {"AssetDirection_backward", TypeInfo_ID_AssetDirection, TypeInfo_ID_i32, MemberKind_enum, 4, 0, 0, 0, 176},
  {"AssetDirection_horizontal", TypeInfo_ID_AssetDirection, TypeInfo_ID_i32, MemberKind_enum, 5, 0, 0, 0, 177},
  {"AssetDirection_vertical", TypeInfo_ID_AssetDirection, TypeInfo_ID_i32, MemberKind_enum, 6, 0, 0, 0, 178},
  {"AssetDirection_count", TypeInfo_ID_AssetDirection, TypeInfo_ID_i32, MemberKind_enum, 7, 0, 0, 0, 179},
  {"AssetMoveState_unspecified", TypeInfo_ID_AssetMoveState, TypeInfo_ID_i32, MemberKind_enum, 0, 0, 0, 0, 180},
  {"AssetMoveState_standing", TypeInfo_ID_AssetMoveState, TypeInfo_ID_i32, MemberKind_enum, 1, 0, 0, 0, 181},
  {"AssetMoveState_running", TypeInfo_ID_AssetMoveState, TypeInfo_ID_i32, MemberKind_enum, 2, 0, 0, 0, 182},
  {"AssetMoveState_walking", TypeInfo_ID_AssetMoveState, TypeInfo_ID_i32, MemberKind_enum, 3, 0, 0, 0, 183},
  {"AssetMoveState_jumping", TypeInfo_ID_AssetMoveState, TypeInfo_ID_i32, MemberKind_enum, 4, 0, 0, 0, 184},
  {"AssetMoveState_falling", TypeInfo_ID_AssetMoveState, TypeInfo_ID_i32, MemberKind_enum, 5, 0, 0, 0, 185},
  {"AssetMoveState_count", TypeInfo_ID_AssetMoveState, TypeInfo_ID_i32, MemberKind_enum, 6, 0, 0, 0, 186},
  {"AssetLivingState_unspecified", TypeInfo_ID_AssetLivingState, TypeInfo_ID_i32, MemberKind_enum, 0, 0, 0, 0, 187},
  {"AssetLivingState_dead", TypeInfo_ID_AssetLivingState, TypeInfo_ID_i32, MemberKind_enum, 1, 0, 0, 0, 188},
  {"AssetLivingState_destroyed", TypeInfo_ID_AssetLivingState, TypeInfo_ID_i32, MemberKind_enum, 2, 0, 0, 0, 189},
  {"AssetLivingState_count", TypeInfo_ID_AssetLivingState, TypeInfo_ID_i32, MemberKind_enum, 3, 0, 0, 0, 190},
  {"AssetClass_unspecified", TypeInfo_ID_AssetClass, TypeInfo_ID_i32, MemberKind_enum, 0, 0, 0, 0, 191},
  {"AssetClass_science", TypeInfo_ID_AssetClass, TypeInfo_ID_i32, MemberKind_enum, 1, 0, 0, 0, 192},
  {"AssetClass_count", TypeInfo_ID_AssetClass, TypeInfo_ID_i32, MemberKind_enum, 2, 0, 0, 0, 193},
  {"AssetColor_unspecified", TypeInfo_ID_AssetColor, TypeInfo_ID_i32, MemberKind_enum, 0, 0, 0, 0, 194},
  {"AssetColor_dark", TypeInfo_ID_AssetColor, TypeInfo_ID_i32, MemberKind_enum, 1, 0, 0, 0, 195},
  {"AssetColor_light", TypeInfo_ID_AssetColor, TypeInfo_ID_i32, MemberKind_enum, 2, 0, 0, 0, 196},
  {"AssetColor_caramel", TypeInfo_ID_AssetColor, TypeInfo_ID_i32, MemberKind_enum, 3, 0, 0, 0, 197},
  {"AssetColor_blue", TypeInfo_ID_AssetColor, TypeInfo_ID_i32, MemberKind_enum, 4, 0, 0, 0, 198},
  {"AssetColor_green", TypeInfo_ID_AssetColor, TypeInfo_ID_i32, MemberKind_enum, 5, 0, 0, 0, 199},
  {"AssetColor_red", TypeInfo_ID_AssetColor, TypeInfo_ID_i32, MemberKind_enum, 6, 0, 0, 0, 200},
  {"AssetColor_count", TypeInfo_ID_AssetColor, TypeInfo_ID_i32, MemberKind_enum, 7, 0, 0, 0, 201},
  {"tracking_id", TypeInfo_ID_AssetAttributes, TypeInfo_ID_i64, MemberKind_value, 0, (size_t)&((AssetAttributes*)0)->tracking_id, 0, 0, 202},
  {"variation_number", TypeInfo_ID_AssetAttributes, TypeInfo_ID_u32, MemberKind_value, 0, (size_t)&((AssetAttributes*)0)->variation_number, 0, 0, 203},
  {"direction", TypeInfo_ID_AssetAttributes, TypeInfo_ID_AssetDirection, MemberKind_value, 0, (size_t)&((AssetAttributes*)0)->direction, 0, 0, 204},
  {"move_state", TypeInfo_ID_AssetAttributes, TypeInfo_ID_AssetMoveState, MemberKind_value, 0, (size_t)&((AssetAttributes*)0)->move_state, 0, 0, 205},
  {"asset_class", TypeInfo_ID_AssetAttributes, TypeInfo_ID_AssetClass, MemberKind_value, 0, (size_t)&((AssetAttributes*)0)->asset_class, 0, 0, 206},
  {"color", TypeInfo_ID_AssetAttributes, TypeInfo_ID_AssetColor, MemberKind_value, 0, (size_t)&((AssetAttributes*)0)->color, 0, 0, 207},
  {"bitflags", TypeInfo_ID_AssetAttributes, TypeInfo_ID_u32, MemberKind_value, 0, (size_t)&((AssetAttributes*)0)->bitflags, 0, 0, 208},
  {"living_state", TypeInfo_ID_AssetAttributes, TypeInfo_ID_AssetLivingState, MemberKind_value, 0, (size_t)&((AssetAttributes*)0)->living_state, 0, 0, 209},
  {"filepath", TypeInfo_ID_AssetSpec, TypeInfo_ID_char, MemberKind_pointer, 0, (size_t)&((AssetSpec*)0)->filepath, 0, 1, 210},
  {"asset_type", TypeInfo_ID_AssetSpec, TypeInfo_ID_AssetType, MemberKind_value, 0, (size_t)&((AssetSpec*)0)->asset_type, 0, 0, 211},
  {"asset_attributes", TypeInfo_ID_AssetSpec, TypeInfo_ID_AssetAttributes, MemberKind_value, 0, (size_t)&((AssetSpec*)0)->asset_attributes, 0, 0, 212},
  {"use_anchor", TypeInfo_ID_AssetSpec, TypeInfo_ID_b32, MemberKind_value, 0, (size_t)&((AssetSpec*)0)->use_anchor, 0, 0, 213},
  {"anchor_x", TypeInfo_ID_AssetSpec, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((AssetSpec*)0)->anchor_x, 0, 0, 214},
  {"anchor_y", TypeInfo_ID_AssetSpec, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((AssetSpec*)0)->anchor_y, 0, 0, 215},
  {"DummyUnion_Type_dummy_val", TypeInfo_ID_DummyUnion_Type, TypeInfo_ID_i32, MemberKind_enum, 0, 0, 0, 0, 216},
  {"dummy_val", TypeInfo_ID_DummyUnion, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((DummyUnion*)0)->dummy_val, 0, 0, 217},
  {"handle", TypeInfo_ID_TextureAsset, TypeInfo_ID_void, MemberKind_pointer, 0, (size_t)&((TextureAsset*)0)->handle, 0, 0, 218},
  {"left", TypeInfo_ID_TextureAsset, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((TextureAsset*)0)->left, 0, 0, 219},
  {"right", TypeInfo_ID_TextureAsset, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((TextureAsset*)0)->right, 0, 0, 220},
  {"top", TypeInfo_ID_TextureAsset, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((TextureAsset*)0)->top, 0, 0, 221},
  {"bottom", TypeInfo_ID_TextureAsset, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((TextureAsset*)0)->bottom, 0, 0, 222},
  {"px_width", TypeInfo_ID_TextureAsset, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((TextureAsset*)0)->px_width, 0, 0, 223},
  {"anchor_x", TypeInfo_ID_TextureAsset, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((TextureAsset*)0)->anchor_x, 0, 0, 224},
  {"ArchiveEntryType_none", TypeInfo_ID_ArchiveEntryType, TypeInfo_ID_i32, MemberKind_enum, 0, 0, 0, 0, 225},
  {"ArchiveEntryType_texture_atlas", TypeInfo_ID_ArchiveEntryType, TypeInfo_ID_i32, MemberKind_enum, 1, 0, 0, 0, 226},
  {"top", TypeInfo_ID_PackedTexture, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((PackedTexture*)0)->top, 0, 0, 227},
  {"anchor_x", TypeInfo_ID_PackedTexture, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((PackedTexture*)0)->anchor_x, 0, 0, 228},
  {"asset_type", TypeInfo_ID_PackedTexture, TypeInfo_ID_AssetType, MemberKind_value, 0, (size_t)&((PackedTexture*)0)->asset_type, 0, 0, 229},
  {"attributes", TypeInfo_ID_PackedTexture, TypeInfo_ID_AssetAttributes, MemberKind_value, 0, (size_t)&((PackedTexture*)0)->attributes, 0, 0, 230},
  {"type", TypeInfo_ID_ArchiveEntryHeader_texture_atlas, TypeInfo_ID_ArchiveEntryType, MemberKind_value, 0, (size_t)&((ArchiveEntryHeader_texture_atlas*)0)->type, 0, 0, 231},
  {"texture_handle", TypeInfo_ID_ArchiveEntryHeader_texture_atlas, TypeInfo_ID_void, MemberKind_pointer, 0, (size_t)&((ArchiveEntryHeader_texture_atlas*)0)->texture_handle, 0, 0, 232},
  {"png_size", TypeInfo_ID_ArchiveEntryHeader_texture_atlas, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((ArchiveEntryHeader_texture_atlas*)0)->png_size, 0, 0, 233},
  {"packed_texture_count", TypeInfo_ID_ArchiveEntryHeader_texture_atlas, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((ArchiveEntryHeader_texture_atlas*)0)->packed_texture_count, 0, 0, 234},
  {"archive_entry_count", TypeInfo_ID_GameArchiveHeader, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((GameArchiveHeader*)0)->archive_entry_count, 0, 0, 235},
  {"x", TypeInfo_ID_vec2, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((vec2*)0)->x, 0, 0, 236},
  {"y", TypeInfo_ID_vec2, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((vec2*)0)->y, 0, 0, 237},
  {"x", TypeInfo_ID_ivec2, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((ivec2*)0)->x, 0, 0, 238},
  {"y", TypeInfo_ID_ivec2, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((ivec2*)0)->y, 0, 0, 239},
  {"x", TypeInfo_ID_vec3, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((vec3*)0)->x, 0, 0, 240},
  {"y", TypeInfo_ID_vec3, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((vec3*)0)->y, 0, 0, 241},
  {"z", TypeInfo_ID_vec3, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((vec3*)0)->z, 0, 0, 242},
  {"x", TypeInfo_ID_ivec3, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((ivec3*)0)->x, 0, 0, 243},
  {"y", TypeInfo_ID_ivec3, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((ivec3*)0)->y, 0, 0, 244},
  {"z", TypeInfo_ID_ivec3, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((ivec3*)0)->z, 0, 0, 245},
  {"bottom_left", TypeInfo_ID_rect2, TypeInfo_ID_vec2, MemberKind_value, 0, (size_t)&((rect2*)0)->bottom_left, 0, 0, 246},
  {"top_right", TypeInfo_ID_rect2, TypeInfo_ID_vec2, MemberKind_value, 0, (size_t)&((rect2*)0)->top_right, 0, 0, 247},
  {"initialized", TypeInfo_ID_GameState, TypeInfo_ID_b32, MemberKind_value, 0, (size_t)&((GameState*)0)->initialized, 0, 0, 248},
  {"highest_entity_id", TypeInfo_ID_GameState, TypeInfo_ID_i64, MemberKind_value, 0, (size_t)&((GameState*)0)->highest_entity_id, 0, 0, 249},
  {"TMP_meat_space", TypeInfo_ID_GameState, TypeInfo_ID_MeatSpace, MemberKind_pointer, 0, (size_t)&((GameState*)0)->TMP_meat_space, 0, 0, 250},
  {"asset_manager", TypeInfo_ID_GameState, TypeInfo_ID_AssetManager, MemberKind_pointer, 0, (size_t)&((GameState*)0)->asset_manager, 0, 0, 251},
  {"perlin_scale", TypeInfo_ID_GameState, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((GameState*)0)->perlin_scale, 0, 0, 252},
  {"editor", TypeInfo_ID_GameState, TypeInfo_ID_Editor, MemberKind_pointer, 0, (size_t)&((GameState*)0)->editor, 0, 0, 253},
  {"dummy_texture", TypeInfo_ID_GameState, TypeInfo_ID_PlatformTexture, MemberKind_value, 0, (size_t)&((GameState*)0)->dummy_texture, 0, 0, 254},
  {"show_grid", TypeInfo_ID_GameState, TypeInfo_ID_b32, MemberKind_value, 0, (size_t)&((GameState*)0)->show_grid, 0, 0, 255},
  {"show_occupied_spaces", TypeInfo_ID_GameState, TypeInfo_ID_b32, MemberKind_value, 0, (size_t)&((GameState*)0)->show_occupied_spaces, 0, 0, 256},
  {"editor_mode", TypeInfo_ID_GameState, TypeInfo_ID_b32, MemberKind_value, 0, (size_t)&((GameState*)0)->editor_mode, 0, 0, 257},
  {"pending_entity_placement_id", TypeInfo_ID_GameState, TypeInfo_ID_MeatSpaceEntityTemplateId, MemberKind_value, 0, (size_t)&((GameState*)0)->pending_entity_placement_id, 0, 0, 258},
  {"draw_path_finding", TypeInfo_ID_GameState, TypeInfo_ID_b32, MemberKind_value, 0, (size_t)&((GameState*)0)->draw_path_finding, 0, 0, 259},
  {"draw_collision_volumes", TypeInfo_ID_GameState, TypeInfo_ID_b32, MemberKind_value, 0, (size_t)&((GameState*)0)->draw_collision_volumes, 0, 0, 260},
  {"step_through_frames", TypeInfo_ID_GameState, TypeInfo_ID_b32, MemberKind_value, 0, (size_t)&((GameState*)0)->step_through_frames, 0, 0, 261},
  {"pending_entity_placement_selection_group", TypeInfo_ID_GameState, TypeInfo_ID_SelectionGroup, MemberKind_value, 0, (size_t)&((GameState*)0)->pending_entity_placement_selection_group, 0, 0, 262},
  {"pending_entity_variation_number", TypeInfo_ID_GameState, TypeInfo_ID_u32, MemberKind_value, 0, (size_t)&((GameState*)0)->pending_entity_variation_number, 0, 0, 263},
  {"allocator", TypeInfo_ID_GameState, TypeInfo_ID_Allocator, MemberKind_value, 0, (size_t)&((GameState*)0)->allocator, 0, 0, 264},
  {"allocator", TypeInfo_ID_TransientState, TypeInfo_ID_Allocator, MemberKind_value, 0, (size_t)&((TransientState*)0)->allocator, 0, 0, 265},
  {"x", TypeInfo_ID_GridCell, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((GridCell*)0)->x, 0, 0, 266},
  {"y", TypeInfo_ID_GridCell, TypeInfo_ID_i32, MemberKind_value, 0, (size_t)&((GridCell*)0)->y, 0, 0, 267},
  {"origin", TypeInfo_ID_Grid, TypeInfo_ID_vec2, MemberKind_value, 0, (size_t)&((Grid*)0)->origin, 0, 0, 268},
  {"cell_width", TypeInfo_ID_Grid, TypeInfo_ID_f32, MemberKind_value, 0, (size_t)&((Grid*)0)->cell_width, 0, 0, 269},
  {"main_archive_async_handle", TypeInfo_ID_AssetManager, TypeInfo_ID_void, MemberKind_pointer, 0, (size_t)&((AssetManager*)0)->main_archive_async_handle, 0, 0, 270},
  {"main_archive", TypeInfo_ID_AssetManager, TypeInfo_ID_GameArchiveHeader, MemberKind_pointer, 0, (size_t)&((AssetManager*)0)->main_archive, 0, 0, 271},
  {"main_archive_last_write_time", TypeInfo_ID_AssetManager, TypeInfo_ID_PlatformFileLastWriteTime, MemberKind_value, 0, (size_t)&((AssetManager*)0)->main_archive_last_write_time, 0, 0, 272},
  {"asset_types_to_atlases", TypeInfo_ID_AssetManager, TypeInfo_ID_void, MemberKind_pointer, 0, (size_t)&((AssetManager*)0)->asset_types_to_atlases, 0, 0, 273},
  {"main_atlas", TypeInfo_ID_AssetManager, TypeInfo_ID_ArchiveEntryHeader_texture_atlas, MemberKind_pointer, 0, (size_t)&((AssetManager*)0)->main_atlas, 0, 0, 274},
  {"capacity", TypeInfo_ID_Allocator, TypeInfo_ID_size_t, MemberKind_value, 0, (size_t)&((Allocator*)0)->capacity, 0, 0, 275},
  {"high_water", TypeInfo_ID_Allocator, TypeInfo_ID_size_t, MemberKind_value, 0, (size_t)&((Allocator*)0)->high_water, 0, 0, 276},
  {"used", TypeInfo_ID_Allocator, TypeInfo_ID_size_t, MemberKind_value, 0, (size_t)&((Allocator*)0)->used, 0, 0, 277},

};

struct TypeInfo {
  TypeInfo_ID id;
  TypeKind kind;
  size_t size;
  int members_start;
};

TypeInfo TypeInfo_custom_type_table[] = {
  {TypeInfo_ID_PlatformTexture, TypeKind_struct, sizeof(PlatformTexture), 0},
  {TypeInfo_ID_PlatformFileLastWriteTime, TypeKind_struct, sizeof(PlatformFileLastWriteTime), 2},
  {TypeInfo_ID_Editor, TypeKind_struct, sizeof(Editor), 0},
  {TypeInfo_ID_MeatSpaceCommand_Type, TypeKind_enum, sizeof(MeatSpaceCommand_Type), 3},
  {TypeInfo_ID_MeatSpaceCommand_move_to, TypeKind_struct, sizeof(MeatSpaceCommand_move_to), 6},
  {TypeInfo_ID_MeatSpaceCommand, TypeKind_union, sizeof(MeatSpaceCommand), 8},
  {TypeInfo_ID_MeatSpaceWeapon_Type, TypeKind_enum, sizeof(MeatSpaceWeapon_Type), 10},
  {TypeInfo_ID_MeatSpaceWeapon_gun, TypeKind_struct, sizeof(MeatSpaceWeapon_gun), 14},
  {TypeInfo_ID_MeatSpaceWeapon_grenade_launcher, TypeKind_struct, sizeof(MeatSpaceWeapon_grenade_launcher), 19},
  {TypeInfo_ID_MeatSpaceWeapon_healing_ray, TypeKind_struct, sizeof(MeatSpaceWeapon_healing_ray), 25},
  {TypeInfo_ID_MeatSpaceWeapon, TypeKind_union, sizeof(MeatSpaceWeapon), 30},
  {TypeInfo_ID_SelectionGroup, TypeKind_enum, sizeof(SelectionGroup), 34},
  {TypeInfo_ID_MeatSpaceEntityTemplateId, TypeKind_enum, sizeof(MeatSpaceEntityTemplateId), 38},
  {TypeInfo_ID_MeatSpaceEntity, TypeKind_struct, sizeof(MeatSpaceEntity), 47},
  {TypeInfo_ID_MeatSpaceBrain_Type, TypeKind_enum, sizeof(MeatSpaceBrain_Type), 67},
  {TypeInfo_ID_MeatSpaceBrain_player, TypeKind_struct, sizeof(MeatSpaceBrain_player), 70},
  {TypeInfo_ID_MeatSpaceBrain, TypeKind_union, sizeof(MeatSpaceBrain), 76},
  {TypeInfo_ID_MeatSpaceProjectile_Type, TypeKind_enum, sizeof(MeatSpaceProjectile_Type), 78},
  {TypeInfo_ID_MeatSpaceProjectile_common, TypeKind_struct, sizeof(MeatSpaceProjectile_common), 82},
  {TypeInfo_ID_MeatSpaceProjectile_entity_targeted, TypeKind_struct, sizeof(MeatSpaceProjectile_entity_targeted), 84},
  {TypeInfo_ID_MeatSpaceProjectile_position_targeted, TypeKind_struct, sizeof(MeatSpaceProjectile_position_targeted), 89},
  {TypeInfo_ID_MeatSpaceProjectile, TypeKind_union, sizeof(MeatSpaceProjectile), 93},
  {TypeInfo_ID_MeatSpaceCamera, TypeKind_struct, sizeof(MeatSpaceCamera), 97},
  {TypeInfo_ID_PositionGridBucketNode, TypeKind_struct, sizeof(PositionGridBucketNode), 103},
  {TypeInfo_ID_CollisionVolume_Type, TypeKind_enum, sizeof(CollisionVolume_Type), 105},
  {TypeInfo_ID_CollisionVolume_common, TypeKind_struct, sizeof(CollisionVolume_common), 110},
  {TypeInfo_ID_CollisionVolume_box, TypeKind_struct, sizeof(CollisionVolume_box), 113},
  {TypeInfo_ID_CollisionVolume_circle, TypeKind_struct, sizeof(CollisionVolume_circle), 117},
  {TypeInfo_ID_CollisionVolume_elipse, TypeKind_struct, sizeof(CollisionVolume_elipse), 121},
  {TypeInfo_ID_CollisionVolume, TypeKind_union, sizeof(CollisionVolume), 124},
  {TypeInfo_ID_MeatSpaceEntityTemplate, TypeKind_struct, sizeof(MeatSpaceEntityTemplate), 129},
  {TypeInfo_ID_MeatSpaceEntityTemplateCollection, TypeKind_struct, sizeof(MeatSpaceEntityTemplateCollection), 141},
  {TypeInfo_ID_MeatSpace, TypeKind_struct, sizeof(MeatSpace), 145},
  {TypeInfo_ID_AssetType, TypeKind_enum, sizeof(AssetType), 161},
  {TypeInfo_ID_AssetDirection, TypeKind_enum, sizeof(AssetDirection), 172},
  {TypeInfo_ID_AssetMoveState, TypeKind_enum, sizeof(AssetMoveState), 180},
  {TypeInfo_ID_AssetLivingState, TypeKind_enum, sizeof(AssetLivingState), 187},
  {TypeInfo_ID_AssetClass, TypeKind_enum, sizeof(AssetClass), 191},
  {TypeInfo_ID_AssetColor, TypeKind_enum, sizeof(AssetColor), 194},
  {TypeInfo_ID_AssetAttributes, TypeKind_struct, sizeof(AssetAttributes), 202},
  {TypeInfo_ID_AssetSpec, TypeKind_struct, sizeof(AssetSpec), 210},
  {TypeInfo_ID_DummyUnion_Type, TypeKind_enum, sizeof(DummyUnion_Type), 216},
  {TypeInfo_ID_DummyUnion, TypeKind_union, sizeof(DummyUnion), 217},
  {TypeInfo_ID_TextureAsset, TypeKind_struct, sizeof(TextureAsset), 218},
  {TypeInfo_ID_ArchiveEntryType, TypeKind_enum, sizeof(ArchiveEntryType), 225},
  {TypeInfo_ID_PackedTexture, TypeKind_struct, sizeof(PackedTexture), 227},
  {TypeInfo_ID_ArchiveEntryHeader_texture_atlas, TypeKind_struct, sizeof(ArchiveEntryHeader_texture_atlas), 231},
  {TypeInfo_ID_GameArchiveHeader, TypeKind_struct, sizeof(GameArchiveHeader), 235},
  {TypeInfo_ID_vec2, TypeKind_struct, sizeof(vec2), 236},
  {TypeInfo_ID_ivec2, TypeKind_struct, sizeof(ivec2), 238},
  {TypeInfo_ID_vec3, TypeKind_struct, sizeof(vec3), 240},
  {TypeInfo_ID_ivec3, TypeKind_struct, sizeof(ivec3), 243},
  {TypeInfo_ID_rect2, TypeKind_struct, sizeof(rect2), 246},
  {TypeInfo_ID_GameState, TypeKind_struct, sizeof(GameState), 248},
  {TypeInfo_ID_TransientState, TypeKind_struct, sizeof(TransientState), 265},
  {TypeInfo_ID_GridCell, TypeKind_struct, sizeof(GridCell), 266},
  {TypeInfo_ID_Grid, TypeKind_struct, sizeof(Grid), 268},
  {TypeInfo_ID_AssetManager, TypeKind_struct, sizeof(AssetManager), 270},
  {TypeInfo_ID_Allocator, TypeKind_struct, sizeof(Allocator), 275},

};

struct UnionMemberInfo {
  TypeInfo_ID union_type_id;
  i32 type;
  TypeInfo_ID union_member_type_id;
};

UnionMemberInfo TypeInfo_union_member_table[] = {
  {TypeInfo_ID_MeatSpaceCommand, MeatSpaceCommand_Type_move_to, TypeInfo_ID_MeatSpaceCommand_move_to},
  {TypeInfo_ID_MeatSpaceWeapon, MeatSpaceWeapon_Type_gun, TypeInfo_ID_MeatSpaceWeapon_gun},
  {TypeInfo_ID_MeatSpaceWeapon, MeatSpaceWeapon_Type_grenade_launcher, TypeInfo_ID_MeatSpaceWeapon_grenade_launcher},
  {TypeInfo_ID_MeatSpaceWeapon, MeatSpaceWeapon_Type_healing_ray, TypeInfo_ID_MeatSpaceWeapon_healing_ray},
  {TypeInfo_ID_MeatSpaceBrain, MeatSpaceBrain_Type_player, TypeInfo_ID_MeatSpaceBrain_player},
  {TypeInfo_ID_MeatSpaceProjectile, MeatSpaceProjectile_Type_common, TypeInfo_ID_MeatSpaceProjectile_common},
  {TypeInfo_ID_MeatSpaceProjectile, MeatSpaceProjectile_Type_entity_targeted, TypeInfo_ID_MeatSpaceProjectile_entity_targeted},
  {TypeInfo_ID_MeatSpaceProjectile, MeatSpaceProjectile_Type_position_targeted, TypeInfo_ID_MeatSpaceProjectile_position_targeted},
  {TypeInfo_ID_CollisionVolume, CollisionVolume_Type_common, TypeInfo_ID_CollisionVolume_common},
  {TypeInfo_ID_CollisionVolume, CollisionVolume_Type_box, TypeInfo_ID_CollisionVolume_box},
  {TypeInfo_ID_CollisionVolume, CollisionVolume_Type_circle, TypeInfo_ID_CollisionVolume_circle},
  {TypeInfo_ID_CollisionVolume, CollisionVolume_Type_elipse, TypeInfo_ID_CollisionVolume_elipse},
  {TypeInfo_ID_DummyUnion, DummyUnion_Type_dummy_val, TypeInfo_ID_i32},
};
